name: CI

on:
  push:
    branches:
      - main
  
env:
  APP_LOCATION: app/build/outputs/apk/debug/app-debug.apk
  ORG_NAME: Wednesday-Test # The organisation name
  GROUP_NAME: Testers # The group name, you can create as many as you want but mention the one you want to notify
  APP_NAME: Android-Template # The app name, under wh
  
  
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Ktlint
        run: ./gradlew ktlint
      - name: Lint
        run: ./gradlew lintRelease

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Unit tests
        run: ./gradlew testDebugUnitTest
        
